### ISSUE TITLE
Implement JWT in place of sessions in the controllers

### ISSUE THREAD

**Issue by Swap76** [Swap76/NodeJS_Mongo_BoilerPlate#1]
- [ ] Login

- [ ] Logout

- [ ] Checkuser middlewear for authentication

**Comment by Leonardojrr** [comment]
Can i use passport.js ?

**Comment by Swap76** [comment]
yes you can :-)
just make sure the project should have only passport.js for Auth

**Comment by Swap76** [comment]
Should I assign the issue to @Leonardojrr

**Comment by Leonardojrr** [comment]
please

**Comment by whyDontI** [comment]
@Leonardojrr Are you still working on this issue?

**Comment by Swap76** [comment]
@Leonardojrr Please tell us the status of issue
