### ISSUE TITLE
Add Husky Hook 

### ISSUE THREAD

**Issue by Swap76** [Swap76/NodeJS_Mongo_BoilerPlate#28]
Add Hook for git commit & git push

**Comment by surajrockzz** [comment]
can I work on It.
If it is ok. What actions I have to done on commit and push.

**Comment by Swap76** [comment]
@surajrockzz Sorry I have done the changes I haven't pushed because some are breaking changes

**Comment by surajrockzz** [comment]
okay

**Comment by Swap76** [comment]
@surajrockzz If you want some work I have some in my hands
