### ISSUE TITLE
Convert the code into async await in Blog Controller

### ISSUE THREAD

**Issue by Swap76** [Swap76/NodeJS_Mongo_BoilerPlate#3]
Use async-await in place of promises and callbacks in Blog Controller

**Comment by tlcheah2** [comment]
Hi @Swap76 , I would like to work on this issue.

**Comment by Swap76** [comment]
Great :-)

**Comment by tlcheah2** [comment]
#11 Fix this issue

**Comment by Swap76** [comment]
Great Work @tlcheah2
