### ISSUE TITLE
Create a Single function for Joi Validation and use it in Auth and Blog Controller

### ISSUE THREAD

**Issue by Swap76** [Swap76/NodeJS_Mongo_BoilerPlate#5]
A function for Joi validation which will check different inputs and will return the response 

```
const data = {
	email: req.body.email,
	password: req.body.password,
};
const check = {
	email: Joi.string().email().required().trim(),
	password: Joi.string().required().min(8).max(32)
};
const { error } = Joi.validate(data, check);
if (error) {
	res.status(400).send({'error':error.details[0].message});	 
}
```

into something like 

```
const resultfromJoi = checkInput(['email','password'],data);
if(resultfromJoi != true) return resultfromJoi;
```

In case of errors, the resultfromJoi should contain the error message

**Comment by whyDontI** [comment]
Hey, @Swap76 I am working on this issue.

**Comment by Swap76** [comment]
Great, @whyDontI will the assign issue to you :-)

**Comment by whyDontI** [comment]
Hey, @Swap76 
The Async Await in JOI validators is needed.
I just checked it running in one of my APIs. 
It doesn't perform as expected. It is not a blocking process.
