### ISSUE TITLE
Add ESlint into project and add the command for linting and fixing

### ISSUE THREAD

**Issue by Swap76** [Swap76/NodeJS_Mongo_BoilerPlate#6]
Add ESlint into the project with following rules

- 2 space tab allowed
- line break only one code
- ES6 syntax 
- single quotes only 
- semicolon always

also, add .eslintignore
which will exclude node_modules and *.json file and any other if needed

**Comment by lacasera** [comment]
picking up this issue

**Comment by Swap76** [comment]
Great @lacasera :-)

**Comment by lacasera** [comment]
will also add precommit hook to lint files

**Comment by Swap76** [comment]
Ohh that will be super cool @lacasera
