### ISSUE TITLE
Folder structure changes

### ISSUE THREAD

**Issue by whyDontI** [Swap76/NodeJS_Mongo_BoilerPlate#9]
I just wanted to suggest some major folder structure changes, which is, in my opinion, the best folder structure I have used so far.

Please feel free to ask me anything about it. I'll be happy to know your opinions also.

And please let me know if you are ok with these changes so that I can make another pull request on this issue.

I'll just write the folder structure in 'tree ./src' fashion
```
|--Config // Contains all the information about Databases and Servers we'll be connecting to

    |---local.json

    |---stage.json

    |---prod.json

|--DataAdapter

    |--Mongo

        |--Model

            |---user.model.js // Contains User schema

        |--Query

            |---user.query.js // Contains common User queries to be made

        |---connection.js // Used to make the connection to MongoDB (Or any DB) using credentials in config files

|--Logs

    |---reqRes.log // Contains logs of all requests made with responses

|--Middleware

    |--Auth

        |---jwt.auth.js // Used to create JWT token and Validate the same

        |---decryptor.auth.js // Used to decrypt the JWT

        |---encryptor.auth.js // Used to encrypt the JWT

|--Validator

    |--user.validator.js // User validations using Joi

|--Routes

    |--user.routes.js // Contains all user routes

|--Services

    |--user.service.js // Contains business logic for all user routes

|--Util

    |--response.util.js // Contains response functions

Server.js

package.json
```

**Comment by Swap76** [comment]
Yes, will love to try this one out. 

Looks interesting to me

**Comment by whyDontI** [comment]
Thanks @Swap76 I'll make a pull request ASAP.

**Comment by whyDontI** [comment]
Hey, @Swap76 we should create a Gitter room.

**Comment by whyDontI** [comment]
Hey, @Swap76 Is it appropriate to make changes which are this big. How are you gonna handle the merging process? Should I still make a PR?

**Comment by Swap76** [comment]
I was also thinking of this as due to Hacktoberfest many people are working on this. For them, this will create many problems for all the PRs.

Will stop for sometime after some days we can think of changing as after October the repo will be a less active

**Comment by whyDontI** [comment]
Sounds good
